version: '3.1'

services:
  mongodb:
    image: mongo
    restart: always
    # ports:
    #   - 27017:27017
    volumes:
      - labhive_mongodb_prodDB:/data/db
      - labhive_mongodb_prodConfig:/data/configdb
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: example
  
  app:
    image: labhive.prod
    restart: always
    depends_on: 
      - mongodb
    build:
      context: .
    ports:
      - 5002:5000
    environment: 
      PRODUCTION: "1"
      BASE_URL: "https://labhive.de"

volumes:
  labhive_mongodb_prodDB:
    external: true
  labhive_mongodb_prodConfig:
    external: true

