name: "Staging"
on:
  push:
    branches:
      - dev
      - CI
    paths:
      - 'labshare-client/**'
      - '.github/**'
  pull_request:
    branches:
      - dev
      - CI
    paths:
      - 'labshare-client/**'
      - '.github/**'
  

jobs:
  build:
    name: "Build and Push Docker Image"
    runs-on: ubuntu-latest
    steps:
      - name: "Build and Push Docker Image"
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: labhive/labhive
          tags: staging
          path: ./labshare-client
          dockerfile: ./labshare-client/Dockerfile
          build_args: enableDev=true,staging=true

  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: "Deploy"
      uses: appleboy/ssh-action@master
      if: github.event.pull_request.merged == true || github.event_name == 'push'
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          cd LabHive-Staging/labshare-client;
          git reset --hard;
          git pull;

          docker create volume labhive_secret_staging;
          docker run --rm -v $(pwd):/src -v labhive_secret_staging:/dst busybox cp -r /src/secret/. /dst/;

          docker stack deploy -c docker-compose.staging.yml LabHiveStaging;

          if ! docker run --rm -v $(pwd):/app -w /app --network LabHiveStaging_network -e "PRODUCTION=1" node npm run migrations up; then
            docker run --rm -v $(pwd):/app -w /app --network LabHiveStaging_network -e "PRODUCTION=1" node npm run migrations down || true;
            docker service rollback LabHiveStaging_app;
            exit 1;
          fi
